- .github/PULL_REQUEST_TEMPLATE/pull_request_template.md
- .github/docs/pull_request_template.md
Shorten the checklist in the pull request template as there's some duplicate questions. 
Fixes #2
> Shorten checklist in pr template

- .github/workflows/ci-pipeline.yml
- README.md
Updates documentation in README for environment files and type generation.
> Update README to include environment and code generation documentation

- README.md
> Derrick Trang name added

- README.md
> chore: add name to README.

- vitest.config.mts
Gets rid of the `RangeError` like in https://github.com/UoaWDCC/uabc-web/actions/runs/14280913541/job/40030371135
> Fix tests with new min workers

- .github/workflows/ci-pipeline.yml
- src/app/(frontend)/sessions/client-page.tsx
Add some extra changes to match the documentation at https://github.com/marketplace/actions/path-filter
**Runs on code file change**
**Does not run on ignored file change:**
> chore: add output for change check in CI pipeline

- src/app/(frontend)/(dev)/account/client-page.tsx
- src/app/(frontend)/(dev)/account/page.tsx
- src/components/BackNavigationBar.tsx
- src/components/TextInput.tsx
- src/theme/semantics.ts
- src/theme/tokens/colors.ts
I have migrated the `/account` page to Yamada UI.
Closes #44
> I have migrated account page to Yamada UI

- src/app/(frontend)/(dev)/payment/direct-debit/page.tsx
- src/app/(frontend)/(dev)/payment/page.tsx
- src/components/payment/DebitDetailsCard.tsx
- src/components/payment/PaymentInfoCard.tsx
- src/components/payment/PaymentOptionCard.tsx
I have migrated the `/account` page to Yamada UI.
I have also referenced below from Figma.
Closes #46
> Migrated payment page to Yamada UI

- .github/workflows/cd-pipeline.yml
Apparently any step in a GitHub action requires `steps`. 
This fixes it and puts a place holder that echos `To be implemented`. 
Fixes #74
> Put placeholder for production deployment

- .github/ISSUE_TEMPLATE/backend-feature-template.md
- .github/ISSUE_TEMPLATE/bug_report.md
- .github/ISSUE_TEMPLATE/design-template.md
- .github/ISSUE_TEMPLATE/devops-feature-template.md
- .github/ISSUE_TEMPLATE/frontend-feature-template.md
Created a devops feature template and also commented out placeholders so they stay but no longer need to be deleted. 
Also added some placeholders in the design template so our design team has more context. 
Fixes #82
> 82 create devops feature template

- README.md
Update README to provide more information on Biome + more grammatical changes
> docs: add biome to README

- .github/workflows/cd-pipeline.yml
- .github/workflows/ci-pipeline.yml
- .github/workflows/deploy-github-pages.yml
- packages/ui/.storybook/main.ts
- packages/ui/.storybook/manager-head.html
- packages/ui/package.json
- packages/ui/src/components/Button/Button.stories.tsx
- packages/ui/src/components/Colors.stories.tsx
- packages/ui/src/components/Heading/Heading.stories.tsx
- packages/ui/src/components/TextInput/TextInput.stories.tsx
- packages/ui/turbo.json
- pnpm-lock.yaml
- turbo.json
Added GitHub Pages environment configuration to the deployment workflow. This will host the storybook.
The url should be https://uoawdcc.github,io/uabc-web/
Closes #129
> Add storybook github page

- apps/frontend/src/app/auth/(auth)/signup/page.tsx
- apps/frontend/src/components/Composite/auth/EmailSignUpForm.tsx
Migrated the sign up page and form to Yamada UI.
Once this is merged, I'll start on another PR to clean up certain things and migrate the layout.tsx.
After:
Before:
Fixes #92
> refactor: migrate the sign up page and form to Yamada UI.

- .github/workflows/renovate.yml
- renovate.json
This includes a new github action `renovate` which will check for package updates, and upgrades the package if ci passes.
It will help us manage package versions better.
Fixes N/A
> feat(renovate): add renovate for managing packages

- .github/workflows/renovate.yml
- renovate.json
I have added an env for github repository to fix the issue.
I have also simplified renovate configuration.
Closes #180
> fix(renovate): set environment variable for repository in Renovate workflow

- .github/workflows/renovate.yml
I have improved the caching logic for renovate workflow.
Fixes N/A
> fix(renovate): add repoCache input for cache management in Renovate workflow

- renovate.json
I have migrated `renovate.json` to newer format, and also simplified some config.
Closes #186
> refactor(renovate): migrate to new config and simplify

- apps/frontend/package.json
- apps/frontend/src/app/layout.tsx
- packages/test-config/package.json
- packages/test-config/src/configs/backend-config.ts
- packages/test-config/src/configs/base-config.ts
- packages/test-config/src/configs/frontend-config.ts
- packages/test-config/src/setups/dom-setup.ts
- packages/test-config/tsconfig.json
- pnpm-lock.yaml
Added Yamada UI and `ui` repo to frontend.
Closes #245
> feat(yamada): add `yamada-ui` and `@repo/ui` to frontend

- apps/backend/src/business-layer/services/AuthService.test.ts
- apps/backend/src/business-layer/services/AuthService.ts
- apps/backend/src/data-layer/services/AuthDataService.test.ts
- apps/backend/src/payload.config.ts
- apps/backend/src/test-config/mocks/Authentication.mock.ts
- apps/backend/src/test-config/mocks/Booking.mock.ts
- apps/backend/src/test-config/mocks/User.mock.ts
- apps/backend/src/test-config/vitest.setup.ts
- packages/shared/src/schemas/auth.ts
- packages/shared/src/types/auth.ts
- Add separate mock objects for casual, member and admin users with unique IDs and emails. 
- Enable ID control in test environment and fix auth test to use the correct email from created user.
Fixes #254
> feat(mocks): mock auth cookies for better testing

- .github/workflows/ci-pipeline.yml
- .github/workflows/deploy-github-pages.yml
I have removed `.turbo` from cache and updated cache restore/save.
Closes #300
> refactor(ci-pipeline): remove `.turbo` from cache and update cache restore and save

- apps/frontend/package.json
- apps/frontend/src/test-config/vitest.setup.tsx
- pnpm-lock.yaml
The `@repo/ui` package has been added back to frontend dependencies. We pruned in our docker file so that ui package would have been deleted unintentionally. 
Fixes #239
> fix(frontend): add ui package dependency

- .github/ci-actions/build/action.yml
- .github/workflows/ci-pipeline.yml
Created composite build CI action and separated the build to build-client and build-server. 
Fixes #318
> feat: add build composite action and seperate build action in CI

- packages/ui/src/components/Generic/QuickBook/QuickBook.tsx
- packages/ui/src/components/Primitive/MultiSelect/MultiSelect.tsx
- packages/ui/src/components/Primitive/Select/Select.stories.tsx
- packages/ui/src/components/Primitive/Select/Select.tsx
Fixes: ISSUE #404 NOT FOUND
Icon and label of Select are no longer stacked above the dropdown lists of other Select components.
The select field is now padded on both the left and right, preventing text overlap with chevron.
I also fixed the visual bug when Select is in error:
Let me know if you can think of a more elegant workaround than the one I went with.
> fix(select): fix visual Select component bugs

- .github/ci-actions/build-storybook/action.yml
I have added upload artifact step.
Closes #422
> feat(storybook,artifact): add upload artifact step

- apps/backend/src/app/api/admin/semesters/[id]/route.ts
- apps/backend/src/app/api/admin/users/[id]/route.test.ts
- apps/backend/src/app/api/admin/users/[id]/route.ts
Implemented edit user for admins with testing
Fixes #435
> feat(edit user): implemented edit user for admins with testing

- .github/cd-actions/deploy-frontend/action.yml
- .github/ci-actions/build-frontend/action.yml
- .github/ci-actions/comment/action.yml
- .github/workflows/ci-pipeline.yml
- apps/backend/next.config.mjs
- apps/backend/src/app/payload/layout.tsx
- apps/backend/src/payload.config.ts
- apps/frontend/next.config.ts
- apps/frontend/src/lib/api/endpoints/globals.ts
- turbo.json
Created a frontend preview action that automatically builds and pushes your frontend to Cloudflare so that we can preview the deployment within your pull request! 
Also updated the PR message so that it includes both the frontend and storybook preview urls. 
The build is still standard standalone builds, hence fly deployments are unaffected. The only change is the addition of a `NEXT_CONFIG_ENV` that determines if a build is `standalone` or `static`. 
The standard build checks check for standalone while the deployment preview builds static and then sends the static files to cloudflare.  
- Removed the timestamp as it was rather irrelevant due to it waiting for both the builds (hence the timestamp is inaccurate). 
- ~~! Switching fly deployment(removing Fly for frontend) to Cloudflare~~ …
> ci(frontend): create frontend deployment preview action

- apps/backend/src/app/api/admin/game-session-schedules/[id]/route.test.ts
- apps/backend/src/app/api/admin/game-session-schedules/[id]/route.ts
Add GET method for fetching specific game session schedules.
Fixes #355
> feat: add GET by id for game session schedules

- apps/frontend/next.config.ts
- apps/frontend/src/app/layout.tsx
- apps/frontend/src/app/page.test.tsx
- apps/frontend/src/app/page.tsx
- packages/ui/src/components/Composite/AboutUsSection/AboutUsSection.tsx
- packages/ui/src/components/Generic/AboutUsCarousel/AboutUsCarousel.tsx
- packages/ui/src/components/Generic/LocationBubble/LocationBubble.stories.tsx
- packages/ui/src/components/Generic/LocationBubble/LocationBubble.test.tsx
- packages/ui/src/components/Generic/LocationBubble/LocationBubbleCircle.tsx
- packages/ui/src/components/Generic/LocationBubble/LocationBubbleDesktopCard.tsx
- packages/ui/src/components/Generic/LocationBubble/index.tsx
- packages/ui/src/components/Generic/NavigationBar/NavigationBar.test.tsx
- packages/ui/src/components/Generic/NavigationBar/NavigationBar.tsx
- packages/ui/src/components/Generic/NavigationBar/NavigationBarDesktop.tsx
- packages/ui/src/components/Generic/NavigationBar/NavigationBarMobile.tsx
Added home page with placeholder content and is responsive for desktop and mobile devices. Adapted `NavigationBar`, `AboutUsCarousel`, `LocationBubble` components to function as expected in next.js. Added responsive styles to `LocationBubble` component for use on mobile.
Fixes #453
> feat(home): add `Home` page with placeholder content

- .github/workflows/cd-pipeline.yml
I made a mistake of adding an extra closing bracket in CD pipeline. 
Fixes #462
> fix: remove extra closing bracket

- .github/ci-actions/comment/action.yml
- .github/workflows/ci-pipeline.yml
A cool new feature that allows for incremental patches of the deployment status. This way we have messages that gradually update depending on the stage of previews. 
Fixes #455
> feat: add pre and post comment deployment status

- apps/backend/src/app/api/auth/login/route.test.ts
- apps/backend/src/app/api/auth/login/route.ts
Updated login route to return JWT token and updated tests to use regex to verify a valid JWT token is being returned.
Fixes #488
> refactor: return JWT in login route

- apps/frontend/src/components/client/FaqSection.tsx
Changed the media base url for the faq component to correctly use next public api url.
Fixes #512
> fix(frontend): use media base url for faq rich text props

- apps/backend/src/payload.config.ts
Disabled email in dev and tests
Fixes #361
> fix(config): disable email in development

- packages/ui/src/components/Generic/AdminNotAvailableCard/AdminNotAvailableCard.stories.tsx
- packages/ui/src/components/Generic/AdminNotAvailableCard/AdminNotAvailableCard.test.tsx
- packages/ui/src/components/Generic/AdminNotAvailableCard/AdminNotAvailableCard.tsx
- packages/ui/src/components/Generic/AdminNotAvailableCard/index.ts
- packages/ui/src/components/Generic/index.ts
Creates AdminNotAvailableCard component to provide fallback for admin views on mobile until implemented.
Fixes #538
> feat(ui): add AdminNotAvailableCard component

- cspell.json
- packages/ui/.storybook/main.ts
- packages/ui/package.json
- packages/ui/src/components/Composite/BookingConfirmedPopup/BookingConfirmedPopup.stories.tsx
- packages/ui/src/components/Composite/BookingConfirmedPopup/BookingConfirmedPopup.test.tsx
- packages/ui/src/components/Composite/BookingConfirmedPopup/BookingConfirmedPopup.tsx
- packages/ui/src/components/Composite/BookingConfirmedPopup/index.ts
- packages/ui/src/components/Composite/index.ts
- packages/ui/src/components/Generic/UserProfileCard/UserProfileCard.tsx
- pnpm-lock.yaml
I have added a `BookingConfirmed` composite popup component.
- Closes #541
> feat(booking-confirmed-popup): add a booking-confirmed composite component

- packages/theme/src/components/input.ts
- packages/theme/src/components/select.ts
- packages/ui/src/components/Composite/AdminTable/Filter/FilterInput.tsx
- packages/ui/src/components/Composite/AdminTable/Filter/index.tsx
- packages/ui/src/components/Primitive/FormComponents.stories.tsx
- packages/ui/src/components/Primitive/MultiSelect/MultiSelect.test.tsx
- packages/ui/src/components/Primitive/MultiSelect/MultiSelect.tsx
- packages/ui/src/components/Primitive/Select/Select.test.tsx
- packages/ui/src/components/Primitive/Select/Select.tsx
I have fixed inconsistencies between select and text input fields.
**I have changed default select component size to be "lg".**
> [!IMPORTANT]
> BREAKING CHANGE: Deprecated Label in Select and MultiSelect.
> feat(input, select, multi-select)!: update styles of form components to be consistent

- apps/backend/src/app/api/globals/tos/route.test.ts
- apps/backend/src/app/api/globals/tos/route.ts
- apps/backend/src/app/payload/admin/importMap.js
- apps/backend/src/data-layer/globals/Tos.ts
- apps/backend/src/payload.config.ts
- biome.json
- packages/shared/src/payload-types.ts
I've added TOS global config.
- Closes #566
> feat(tos): implement Terms of Service global configuration and API route

- biome.json
- lefthook.yml
I have adjusted lefthook configuration according to the team's preference.
Please run
```bash
pnpm lefthook uninstall  && pnpm lefthook install
```
> chore(biome,lefthook): update biome configuration and add pre-commit checks

- .vscode/settings.json
- apps/backend/next.config.mjs
I have fixed auth headers for backend in next config. I've also updated vscode settings.
> fix(auth,headers,backend): fix auth headers for backend

- packages/shared/src/schemas/globals/footer.ts
Fixes the footer parsing error. 
> refactor: omit id from Footer schema

- .github/workflows/cd-pipeline.yml
> build: add smtp secrets to cd pipeline

- apps/backend/src/app/api/auth/verification-code/route.test.ts
- apps/backend/src/app/api/auth/verification-code/route.ts
- packages/ui/src/components/Generic/LoginPanel/LoginPanel.tsx
- packages/ui/src/components/Generic/RegisterPanel/RegisterPanel.tsx
The email verification code route should return a `409` if a user already exists. 
Fixes #626
> fix(auth): return 409 existing users on verification code route

- apps/backend/src/app/api/admin/users/[id]/route.test.ts
- apps/backend/src/app/api/admin/users/route.test.ts
- apps/backend/src/business-layer/security/authentication.ts
Now our authentication shouldn't dump logs that we don't really care about. 
Fixes # no issue
> fix(middleware)!: remove redundant console logging

- apps/backend/vitest.config.ts
I have fixed coverage not properly excluding [[...segments]]/page.tsx
- Closes #663
> fix(vitest, coverage): fix coverage exclusion for backend

- apps/backend/src/app/api/admin/bookings/[id]/route.test.ts
- apps/backend/src/app/api/admin/bookings/[id]/route.ts
- packages/shared/src/schemas/booking.ts
Implemented PATCH route for bookings for admins with testing 
Fixes #689
> feat(PATCH booking): implemented edit booking route for admins

- apps/frontend/src/context/AuthContext.test.tsx
- apps/frontend/src/context/AuthContext.tsx
- packages/ui/src/hooks/storage/__tests__/localStorageManager.events.test.ts
- packages/ui/src/hooks/storage/localStorageManager.ts
- packages/ui/src/test-config/localStorage-test-utils.ts
Now the client side has fully synced with local storage, and properly invalidates JWT token.
- Closes #702
Showcase sent in discord, I will not be posting it here due to privacy concerns.
> fix(auth): fix invalidation and local storage event handling

- apps/frontend/src/components/client/LocationBubbleSection.tsx
- packages/ui/src/components/Generic/LocationBubble/index.tsx
- packages/ui/src/components/Generic/NavigationBar/NavigationBar.test.tsx
- packages/ui/src/components/Generic/NavigationBar/NavigationBarButton.tsx
- packages/ui/src/components/Generic/NavigationBar/NavigationBarMobile.tsx
- packages/ui/src/utils/path.test.ts
- packages/ui/src/utils/path.ts
I have fixed navbar indicator not working due to trailing slash.
I've also fixed the issue where location bubble section was too short.
> refactor(navigation): enhance path handling and improve UI components

- apps/backend/src/app/api/events/route.test.ts
- apps/backend/src/app/api/events/route.ts
api/events getAllEvents route implemented with testing
Fixes #761
> feat(events): getallevents route implemented
