UoaWDCC/uabc-web

.github/workflows/notifcation.yml
This pull request migrates the notification workflow from the old UABC-portal GitHub. 
* Introduces new secret, `DISCORD_WEBHOOK_URL` which is just the discord web hook url you copy.
=> Migrates notification workflow from old portal

README.md, src/app/example-double-admin-count/route.test.ts, src/app/example-double-admin-count/route.ts, src/collections/Admin.ts, src/payload-types.ts, src/payload.config.ts
The old name `User` was not appropriate as users should not have access to the backend schema directly through the admin view
=> Rename Users collection to Admin and update related references

.github/ISSUE_TEMPLATE/backend-feature-template.md, README.md
This pull request changes the environment section of README to not use a codeblock of .env.example as this would require a new PR every time the env is changed. 
Now tells developers to copy the `.env.example` file and change it to `.env`
=> Update README Environment Section

.github/workflows/ci-pipeline.yml, vitest.config.mts
There seemed to be some type of concurrency issue with the mongoDB tests. Hopefully this PR addresses it by limiting vitest to only have 1 worker in CI (example of fail https://github.com/UoaWDCC/uabc-web/actions/runs/14280358636/job/40029176424)
https://github.com/shelfio/jest-mongodb/issues/366
Closes #32
=> configure maxWorkers for MongoDB memory server stability in CI

.gitignore, src/app/(frontend)/privacy/page.tsx, src/app/(frontend)/providers.tsx, src/theme/index.ts, src/theme/semantics.ts, src/theme/tokens/colors.ts, src/theme/tokens/fonts.ts, src/theme/tokens/index.ts
I have migrated the privacy policy page to Yamada UI, with minor styling.
I have also moved theme config to its own directory to let us maintain custom themes easier as we will have our own design system soon.
I am open to any suggestions such as the global font and the fallback that we are using.
Closes #36
=> Made migration to yamada-ui with minor styling

.github/workflows/ci-pipeline.yml, vitest.config.mts
The main issue is in the should_skip filter, which is incorrectly configured. The current implementation skips all checks if a single file like a markdown file or config file changes, even if code files were also changed. Instead, we need to separate the filtering logic to skip only when exclusively non-code files changed.
=> change matching pattern on CI pipeline to allow tests to run on code changes

src/app/(frontend)/admin/page.tsx, src/app/(frontend)/admin/view-sessions/[gameSessionId]/client-page.tsx, src/components/Heading.tsx, src/components/Icons.tsx, src/components/admin/DashboardButton.tsx
I have migrated the `/admin` page to Yamada UI.
I intentionally did not change `<MemberApprovalPing />` because I don't know the original location pre-migration. This can be done later.
Some implementation such as `tracking-tight` is a tailwind custom styling, so I have left it commented out in case we need to refer it back later.
Closes #40
=> Migrated admin root page tailwind to Yamada UI

.github/workflows/cd-pipeline.yml, apps/backend/Dockerfile, apps/backend/fly.staging.toml, apps/frontend/Dockerfile, apps/frontend/fly.staging.toml
I have found a way to enable remote caching on fly deployment, and when I ran them locally on my terminal, it did say remote caching is enabled, but I am not sure if it will actually hit the cache.
Closes #127
=> Enable remote caching on fly deployment

apps/portal/src/types/auth.ts
Updated user info response schema by making `hd` and `family_name` optional. Updated tests for this will be included in other PRs.
Fixes #110
=> refactor: updated user info response schema

package.json, packages/ui/.storybook/main.ts, packages/ui/package.json, packages/ui/src/components/Image/Image.stories.tsx, packages/ui/src/components/Image/Image.test.tsx, packages/ui/src/components/Image/Image.tsx, packages/ui/src/components/Image/base.tsx, packages/ui/src/components/Image/index.ts, packages/ui/src/components/Image/types.ts, packages/ui/src/test-config/constants.ts, packages/ui/src/test-utils/render.tsx, pnpm-lock.yaml, turbo.json
I have implemented a custom `<Image />` component wrapper with Yamada UI in packages.
> [!NOTE]
> The storybook has been updated from `react-vite` to `nextjs`, and changed its script.
Closes #250
=> feat(image): implement custom `Image` component with Next.js and Yamada UI integration

.github/workflows/ci-pipeline.yml
Fixes the issue where preview storybook deployment would run on master branch. 
Fixes #448 
Seems to cancel the `comment` job as well if storybook preview is disabled. 
Tested in [80b2231](https://github.com/UoaWDCC/uabc-web/pull/449/commits/80b223187549cb7d0d8ccd8d8c3d1d58a1d62b4c).
=> fix(ci): skip storybook deploy on master branch

.github/cd-actions/deploy-frontend/action.yml, .github/cd-actions/deploy-storybook/action.yml, .github/workflows/ci-pipeline.yml
Removed the `GITHUB_TOKEN` input for preview deployments. This no longer results in the PR spam of auto preview deployments. 
Fixes #472 
No longer the 
`@github-actions github-actions bot deployed to preview`
=> build: remove auto deployment message within pull requests

.github/cd-actions/deploy-backend/action.yml, .github/workflows/cd-pipeline.yml, apps/backend/fly.production.toml, apps/backend/turbo.json, turbo.json
This PR solves the problem where we were semi using our production as staging. I've separated the build scripts so that frontend and backend now both have dedicated staging and production environments. 
I've also created a composite server deployment action to avoid duplicating the same code. 
Server staging: https://server-staging.uoabadminton.co.nz
Server production: https://server.uoabadminton.co.nz
Client staging: https://staging.uoabadminton.co.nz
Client production: https://uoabadminton.co.nz
Fixes #517 
Isn't really feasible to test
=> refactor(cd): seperate staging and production environments

packages/ui/src/components/Generic/NavigationBar/NavigationBarDesktop.tsx
Introduces an indicator position state variable that is changed when navbar items are clicked. Adds an effect hook to set up the hovered index and initial index upon path change for redirections outside of nav items.
Fixes #603 
Before:
https://github.com/user-attachments/assets/9086f91f-4adb-44c1-821d-12cc05cf4718
After:
https://github.com/user-attachments/assets/be4f90fd-6df9-4f86-8dda-d859ed9f1ab7
=> fix(navbar): correctly display navbar indicator state

apps/backend/src/data-layer/collections/Authentication.ts, apps/backend/src/data-layer/collections/Event.ts, apps/backend/src/data-layer/collections/GameSessionSchedule.ts, apps/backend/src/data-layer/collections/Media.ts, apps/backend/src/data-layer/collections/Semester.ts, apps/backend/src/data-layer/collections/User.ts
Seeing a bunch of ids aren't very useful. 
BEFORE:
AFTER:
Also fixed the following by adding a `defaultValue`
Fixes #639
=> refactor(collections): add `useAsTitle` for better readability

apps/backend/src/app/api/auth/google/callback/route.test.ts, apps/backend/src/app/api/auth/google/callback/route.ts, apps/backend/src/app/api/auth/login/route.test.ts, apps/backend/src/app/api/auth/login/route.ts
- Omit `remainingSessions` from the JWT payload for all authentication flows.
- Ensures JWTs do not become stale due to session count changes.
- Updates tests to match new JWT payload structure.
- No changes to user schema or business logic; only JWT construction is affected.
- Closes #584
=> fix(auth): omit remainingSessions from JWT payload

apps/frontend/src/components/client/user/ProfileSection.tsx, packages/ui/src/components/Composite/ProfileBookingPanel/ProfileBookingPanel.stories.tsx, packages/ui/src/components/Composite/ProfileBookingPanel/ProfileBookingPanel.test.tsx, packages/ui/src/components/Composite/ProfileBookingPanel/ProfileBookingPanel.tsx, packages/ui/src/components/Generic/BookingCard/BookingCard.test.tsx, packages/ui/src/components/Generic/BookingCard/BookingCard.tsx
- The delete button in the bookings panel is now disabled for users with the 'casual' or 'member' role.
- The user object is passed down to ProfileBookingPanel for role-based UI logic.
- Added a test to ensure the BookingCard disables the delete menu item when required.
- Closes #638
=> feat(profile-booking-panel): disable delete button for casual and member users

packages/test-config/src/setups/db.ts, packages/test-config/src/setups/mongodb-setup.ts
This fixes mongo memory server creating many temp folders during test.
I think the issue was, every test the mongodb-setup was being called and it was creating a new mongo-db instance every single test without clearing previous one.
Closes #670
=> fix(mongo, test, setup): fix mongodb test making many temp folders

apps/backend/src/app/api/bookings/route.ts, packages/shared/src/utils/date.ts
I have made the date related utilities to properly use UTC.
- Closes #675
=> fix(bookings): ensure booking open date calculations use UTC consistently

apps/backend/src/app/api/admin/game-sessions/route.test.ts, apps/backend/src/app/api/admin/game-sessions/route.ts
Adds a POST method at `api/admin/game-sessions` to create a new `GameSession`.
Fixes #696
=> feat(game-sessions): implement admin POST endpoint to create a GameSession

apps/backend/src/app/api/admin/game-sessions/route.test.ts, apps/backend/src/app/api/admin/game-sessions/route.ts, apps/backend/src/data-layer/collections/GameSession.ts, apps/backend/src/data-layer/services/GameSessionDataService.test.ts, apps/backend/src/data-layer/services/GameSessionDataService.ts, apps/backend/src/data-layer/utils/DateUtils.ts, apps/backend/src/test-config/mocks/GameSession.mock.ts, apps/backend/src/utils/date.test.ts, packages/shared/src/mocks/GameSession.mock.ts, packages/shared/src/payload-types.ts, packages/shared/src/schemas/game-session.ts, packages/shared/src/utils/date.ts
There wasn't an `openTime` field in `GameSession` documents previously, this made it a lot more difficult to query within the `data-layer`. This also makes it easier in the frontend to check if any sessions are not open yet. 
All `POST` and `GameSession` related backend routes have been modified to omit `openTime` and to create that field with internal logic. A date util function has been added and tested to get the `openTime` based on a semesters specified open day/time and the actual start time of the `GameSession`.
Fixes #727
=> refactor(game-session): add open time to `GameSession`

.zed/settings.json, apps/backend/src/app/api/semesters/[id]/game-sessions/route.test.ts, apps/backend/src/app/api/semesters/[id]/game-sessions/route.ts, apps/backend/src/data-layer/services/GameSessionDataService.test.ts, apps/backend/src/data-layer/services/GameSessionDataService.ts, packages/shared/src/enums/game-session.ts, packages/shared/src/enums/index.ts, packages/shared/src/enums/search-params.ts
We didn't really have an option to get game sessions by semester. This PR introduces that endpoint so that we can fetch all game session documents based on a semester. 
There are 4 different filter options:
1. Upcoming - Any game sessions that are upcoming (excludes past game sessions)
2. Past - Any game sessions that are past (excludes upcoming game sessions)
3. Current - Any game sessions that are current (excludes past game sessions, or game sessions too far in the future)
4. Default - All of the game sessions
Fixes #724
=> feat(semester): add endpoint to get `GameSession`s by semester

apps/backend/src/app/api/auth/login/route.test.ts, apps/backend/src/app/api/auth/login/route.ts
Previously, we'd get a 500 internal server error if a user had a Google account but attempted to login with standard auth (email/password). 
This PR extends the test coverage for the login route by adding a test case for the "Please login with Google" error, ensuring correct behavior when the password is missing from the authentication record.
> [!NOTE]
> Alternatively, we can enable Google account linking, where if a user signed up with Google, they can add a password to their accounts.
Fixes #751
=> fix(auth): add google login prompt on missing password

apps/backend/src/app/api/auth/register/route.test.ts, apps/backend/src/app/api/auth/register/route.ts
- Fixes #745
I've removed `user` from register response. This wasn't needed and probably reveals more than what we need to regular users, so it is best to remove it. 
Also added a test to cover the scenario where getAuthByEmail throws an unexpected error in /api/auth/register.
=> fix(register): remove user data from response

.github/workflows/ci-pipeline.yml, lefthook.yml, package.json, packages/ui/.storybook/main.ts, packages/ui/package.json, packages/ui/src/components/Generic/AboutUsCard/AboutUsCard.stories.tsx, packages/ui/src/components/Generic/AboutUsCarousel/AboutUsCarousel.stories.tsx, packages/ui/src/components/Generic/AdminTabBar/AdminTabBar.stories.tsx, packages/ui/src/components/Generic/BookingCard/BookingCard.stories.tsx, packages/ui/src/components/Generic/CreateSessionPopUp/CreateSessionPopUp.stories.tsx, packages/ui/src/components/Generic/InputPopUp/InputPopUp.stories.tsx, packages/ui/src/components/Generic/LoginPanel/LoginPanel.stories.tsx, packages/ui/src/components/Generic/QuickBook/QuickBook.stories.tsx, packages/ui/src/components/Generic/RegisterPanel/RegisterPanel.stories.tsx, packages/ui/src/components/Generic/UnderConstructionCard/UnderConstructionCard.stories.tsx, packages/ui/src/components/Primitive/Link/Link.stories.tsx, packages/ui/src/components/Primitive/LoadingStateBar/LoadingStateBar.stories.tsx, patches/@storybook__addon-queryparams@7.0.1.patch, pnpm-lock.yaml
I have changed storybook framework from `nextjs` to `nextjs-vite` which should speed up the time required to open storybook.
It also seemed to be recommended by Storybook to use it over `nextjs`.
> Storybook recommends using the @storybook/nextjs-vite framework
https://storybook.js.org/docs/get-started/frameworks/nextjs?renderer=react#with-vite
I have also patched unsupported storybook plugin to work properly with v9.
=> fix(deps): update Storybook integration to use nextjs-vite and add new patched dependencies

apps/frontend/src/context/AuthContext.tsx
This PR improves the authentication flow in `AuthContext.tsx` by ensuring that authentication-related queries are properly managed during login and logout actions. Specifically:
- Fixes #823
These changes help maintain a consistent and secure authentication state, especially when users log in or out rapidly or across multiple tabs.
- During **login**, before making the authentication request, the token is reset and any cached `["auth", "me"]` queries are removed to prevent potential conflicts or stale data.
- The logic for setting the token after login is moved to the `onSettled` callback to ensure it only updates after the mutation completes.
- During **logout**, both `cancelQueries` and `removeQueries` are called for `["auth", "me"]` to ensure any in-flight queries are stopped and …
=> fix(auth): reset auth queries and token on login and logout

.zed/settings.json, apps/backend/src/app/api/bookings/route.test.ts, apps/backend/src/app/api/bookings/route.ts, apps/backend/src/data-layer/services/BookingDataService.test.ts, apps/backend/src/data-layer/services/BookingDataService.ts, apps/backend/src/data-layer/services/GameSessionDataService.ts, apps/backend/src/data-layer/utils/DateUtils.ts, apps/backend/src/test-config/mocks/Semester.mock.ts, packages/shared/src/utils/booking.ts, packages/shared/src/utils/date.ts, packages/shared/src/utils/index.ts
- Fixes #859 
I forgot to add the logic to check if users have reached their max booking sizes of (2 for members, 1 for casuals). I've fixed up the route and added an extra data service that lets a user fetch their bookings within the current booking week which determines if a user has reached their max limit.
=> fix(bookings-api): enforce max user bookings in a week

apps/frontend/src/app/onboarding/page.tsx, apps/frontend/src/components/client/user/OnboardingClient.tsx, apps/frontend/src/components/client/user/OnboardingSection.test.tsx, apps/frontend/src/components/client/user/OnboardingSection.tsx, apps/frontend/src/components/server/OnboardingServerSection.tsx, apps/frontend/src/services/cms/onboarding/OnboardingService.ts, packages/shared/src/schemas/globals/onboarding.ts, packages/shared/src/types/globals/index.ts, packages/shared/src/types/globals/onboarding.ts, packages/ui/src/components/Generic/RegisterFlow/CasualInfoForm/CasualInfoForm.stories.tsx, packages/ui/src/components/Generic/RegisterFlow/CasualInfoForm/CasualInfoForm.test.tsx, packages/ui/src/components/Generic/RegisterFlow/CasualInfoForm/CasualInfoForm.tsx, packages/ui/src/components/Generic/RegisterFlow/RegisterFlow.stories.tsx, packages/ui/src/components/Generic/RegisterFlow/RegisterFlow.test.tsx, packages/ui/src/components/Generic/RegisterFlow/RegisterFlow.tsx, packages/ui/src/test-config/mocks/CasualInfoForm.mock.ts
- Changed the schema used in the `OnboardingService` to correctly parse the api response that uses `data: { ... }`
- Created `OnboardingServerSection` that fetches the onboarding global at build time and passes the data down to the `RegisterFlow` and `CasualInfoForm` components
Fixes #838
=> feat(onboarding): use fetched onboarding global
